// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAohbphzYpjoLxBKQ_ZenDQf_FIjdhRL5Y',
    appId: '1:745004706831:web:62f3d9ecc61c38a7c6477a',
    messagingSenderId: '745004706831',
    projectId: 'must-do-tasks',
    authDomain: 'must-do-tasks.firebaseapp.com',
    storageBucket: 'must-do-tasks.firebasestorage.app',
    measurementId: 'G-SH0XXT9LXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPIJv-5LeIedXahi7cILgqPXbouBNgrWI',
    appId: '1:745004706831:android:883d1fe37dd2e06dc6477a',
    messagingSenderId: '745004706831',
    projectId: 'must-do-tasks',
    storageBucket: 'must-do-tasks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOGN1_H2_DOgzhz4USA7kYNve0rE46HQ',
    appId: '1:745004706831:ios:75b3c40f1f53c1b5c6477a',
    messagingSenderId: '745004706831',
    projectId: 'must-do-tasks',
    storageBucket: 'must-do-tasks.firebasestorage.app',
    iosBundleId: 'com.fo.mustDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBOGN1_H2_DOgzhz4USA7kYNve0rE46HQ',
    appId: '1:745004706831:ios:75b3c40f1f53c1b5c6477a',
    messagingSenderId: '745004706831',
    projectId: 'must-do-tasks',
    storageBucket: 'must-do-tasks.firebasestorage.app',
    iosBundleId: 'com.fo.mustDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAohbphzYpjoLxBKQ_ZenDQf_FIjdhRL5Y',
    appId: '1:745004706831:web:15bbd5bb528be651c6477a',
    messagingSenderId: '745004706831',
    projectId: 'must-do-tasks',
    authDomain: 'must-do-tasks.firebaseapp.com',
    storageBucket: 'must-do-tasks.firebasestorage.app',
    measurementId: 'G-W8E2KWZGX1',
  );
}
